---
title: "Computational Finance | pg.2"
date: "October 23, 2016"
---
 - assign date indices
```{r}
price_1 <- sbux_prices_df["3/1/1994", 1]
price_2 <- sbux_prices_df["3/1/1995", 1]
print(price_1)
print(price_2)
```
 - plot `Adj.Close`
```{r}
plot(sbux_df$Adj.Close, type = "l", col="blue", lwd=2,
     ylab="Adjusted Close",
     main="Monthly Closing Price of Starbucks (SBUX)")
     legend(x='topleft', legend='Starbucks (SBUX)',
     lty=1, lwd=2, col='blue')
```
 - assign `Adj.Close` column to `sbux_prices_df`
```{r}
sbux_prices_df <- sbux_df[, "Adj.Close", drop=FALSE]
```
 - assign total number of rows to n
```{r}
n <- nrow(sbux_prices_df)
```
 - assign simple return to `sbux_ret`
```{r}
sbux_ret <- (sbux_prices_df[2:n,1] - sbux_prices_df[1:(n-1), 1])/sbux_prices_df[1:(n-1), 1]
class(sbux_ret) # numeric
```
 - dates as column names
 ```{r}
names(sbux_ret) <- sbux_df$Date[2:n]
head(sbux_ret)
sbux_ccret <- log(sbux_prices_df[2:n, 1])-log(sbux_prices_df[1:(n-1), 1])
names(sbux_ccret) <- sbux_df[2:n, 1]
head(sbux_ccret)
```
