---
title: "R Plots | pg.1"
author: "nick3499"
date: "`r Sys.Date()`"
output: html_document
---

```{r plot_1}
x <- seq(-5, 5, 0.3)
y <- 2*x^2 + 5*x-8
plot(x, y, pch = 16, col = "red", xlim = c(-6, 6), ylim = c(-20, 70),
     main = expression(2*x^2 + 5*x - 8), xlab = "X" , ylab = "Y")
lines(x, y)
abline(h = 0)
abline(v = 0)
```

```{r plot_2}
X <- c(1, 2, 3,  4,  5,  6,  7,  8)
Y <- c(2, 6, 7, 10, 17, 19, 23, 29)
plot(X, Y, type = "o", col = "red", xlab = "Annual", ylab = "Profit")
title(main = "Upward Trend", font.main = 1, col.main = "blue")
```

```{r plot_3}
X <- c(1,5.5,10,14.5,19,23.5,28,32.5)
Y <- c(2,6.5,11,15.5,20,24.5,29,33.5)
k <- 8
min <- 2
max <- 23
name <- "Radon"
plot(X, Y, type="o", col="581", xlab = paste(name, "'s Profits", sep = ""),
     ylab = paste("Points from ", min, " to ", max,  sep = ""))
title(main = paste("Sector ", k, " for ", name, sep = ""), font.main = 2,
      col.main = "#CC6600")
```

```{r plot_4}
X <- c(0,5,10,15,20,25,30,35)
Y <- c(2,4,13,13,23,21,32,30)
s <- 8
min <- 2
max <- 30
name <- "Radon"
plot(X, Y, type = "o", col = "red",
     main = paste("Sector ", s, " for ", name, sep = ""), pch = 16, cex = 1.4,
     font.main = 2, col.main = "blue",
     xlab = paste(name, "'s Profits", sep = ""),
     ylab = paste("Points from ", min, " to ", max,  sep = ""))
abline(lm(Y ~ X))
```
